default:
	pdflatex 11-NielsenSun

full:
	pdflatex 11-NielsenSun
	bibtex 11-NielsenSun
	pdflatex 11-NielsenSun
	pdflatex 11-NielsenSun

clean:
	rm -f *.log *.aux *.blg *.bbl *.out *.fdb_latexmk *.synctex.gz *.fls \
		  *.maf *.mtc *.mtc0 *.ptc1 *.toc *.mpx

